---
sidebar: sidebar
permalink: element-legal.html
keywords: copyrights, notice, trademarks, patents, privacy, open source
summary: Legal notices provide access to copyright statements, trademarks, patents, and more.
---

= Legal notices
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
Legal notices provide access to copyright statements, trademarks, patents, and more.

== Copyright

http://www.netapp.com/us/legal/copyright.aspx[^]

== Trademarks

NETAPP, the NETAPP logo, and the marks listed on the NetApp Trademarks page are trademarks of NetApp, Inc. Other company and product names may be trademarks of their respective owners.

http://www.netapp.com/us/legal/netapptmlist.aspx[^]

== Patents

A current list of NetApp owned patents can be found at:

https://www.netapp.com/us/media/patents-page.pdf[^]

== Privacy policy

https://www.netapp.com/us/legal/privacypolicy/index.aspx[^]

== Open source

Notice files provide information about third-party copyright and licenses.

* link:./media/Ember_12.3.pdf[Notice for Ember OS 12.3.1^]
* link:./media/Ember_12.3.pdf[Notice for Ember OS 12.3^]
* link:./media/HealthTools_12.3.pdf[Notice for HealthTools^]
* link:./media/mNode_12.3.pdf[Notice for Management Node 12.3.1^]
* link:./media/mNode_12.3.pdf[Notice for Management Node 12.3^]
* link:./media/mgmt_svcs_2.18.pdf[Notice for Management Services 2.18^]
* link:./media/mgmt_2.17.56_notice.pdf[Notice for Management Services 2.17.56^]
* link:./media/mgmt-217.pdf[Notice for Management Services 2.17.52^]
* link:./media/mgmt-216.pdf[Notice for Management Services 2.16^]
* link:./media/mgmt-214.pdf[Notice for Management Services 2.14^]
* link:./media/mgmt-213.pdf[Notice for Management Services 2.13^]
* link:./media/SolidFire_eSDS_12.3.pdf[Notice for NetApp SolidFire Enterprise SDS^]
* link:./media/storage_firmware_bundle_2.99_notices.pdf[Notice for Storage Firmware Bundle 2.99.2^]
