---
permalink: hardware/concept_rtfi_configure.html
sidebar: sidebar
keywords:
summary:
---

= Configure the Return to Factory Image 
:icons: font
:imagesdir: ../media/

[.lead]
NetApp SolidFire storage systems use the Return To Factory Image (RTFI) process to write a software image to a new node or restore a node to its factory original state. The RTFI process securely erases all existing data and configurations (if any) and installs an unconfigured NetApp Element software image. The RTFI process is available for all SolidFire nodes and can also be used on pre-validated hardware configurations that offer NetApp SolidFire Element X support.

SolidFire systems use one RTFI process for all Element software installations. This includes internal manual installations performed by developers, automatic installations by automated test framework, field installations by service engineers and customers, and installations performed by various integrators and partners. The same RTFI process is used on all SolidFire nodes and nodes that support Element X, regardless of the chassis or node type in use, to automatically fix any issues.

The intended audience for this guide is integrators who install, configure, use, or troubleshoot storage-related issues.
* Linux: You have some background with Linux systems.
* Networking: You have a familiarity with server networking and networked storage, including IP addresses, netmasks, and gateways.

WARNING: The RTFI process is data destructive and securely erases all data and configuration details from the node and installs a new operating system. Verify that the node used for the RTFI process is not active as part of a cluster.

Deploy and install the RTFI ISO image and perform the RTFI process:

* xref:task_rtfi_deployment_options.html[Deployment and installation options]
* xref:task_rtfi_process.html[Perform the Return To Factory Image process]
* xref:task_rtfi_options_menu.html[Return To Factory Image options menu]

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation/[NetApp SolidFire Resources Page^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[Documentation for earlier versions of NetApp SolidFire and Element products^]
