---
permalink: esds/concept_esds_networking_best_practices.html
sidebar: sidebar
keywords: solidfire esds, software-defined storage, networks, linux host routing, networking
summary: Before you install SolidFire eSDS, you should set up the required networks on the storage nodes running RHEL. You are responsible for network routing in your environment. You can use the best practices provided as a framework.
---
= Considerations for network configuration
:icons: font
:imagesdir: ../media/

[.lead]
Before you install SolidFire eSDS, you should set up the required networks on the storage nodes running RHEL. You are responsible for network routing in your environment. You can use the best practices provided as a framework.

[IMPORTANT]
===============================
* Use bonded or teamed interfaces.
* Use the same interface names for all the nodes in the cluster (example: team-mgt for each node's management interface and team-stg for each node's storage interface).
* Ensure that NetworkManager is running.
* Ensure that the NetworkManager-dispatcher-routing-rules package is installed on all storage nodes for policy-based routing.
* See https://www.netapp.com/us/media/tr-4763.pdf[Best Practices for Networking and Network Maintenance on NetApp SolidFire Storage Systems].
* Configure the management and storage networks on each node to use multiple, redundant physical interfaces via bond or team configurations.
===============================

For information about network teaming, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_teaming[Configure network teaming^].
By default, all storage node 10GbE interfaces are enabled with a maximum transmission unit (MTU) of 9000 bytes. For optimal performance, configure all server-side storage interfaces with the same MTU as the NetApp SolidFire storage nodes. You should configure network switches to support an MTU of at least 9016 bytes or more to account for jumbo frame overhead and for proper forwarding through the network. If you want to change this configuration to support a lower MTU setting, you should contact NetApp Support.

See the following table for information about the storage and management networks that SolidFire eSDS requires for the different types of traffic:
[%header,cols=2*]
|===
| Type of network| Description
a|
Storage network
a|

 ** Includes all storage/iSCSI traffic.
 ** Can be routed if you want to mount from hosts located on a different layer 3 network or if you plan to replicate data between clusters.
 ** Should be configured with network interfaces on the same layer 2 broadcast domain.

a|
Management network
a|

 ** Includes all management traffic.
 ** Can be routed if you want to access the cluster API or UI from a different layer 3 network.
 ** Should be configured with network interfaces on the same layer 2 broadcast domain.
|===

TIP: For examples and tips to configure the host network, see link:task_esds_configure_the_interface_config_files.adoc[here^].

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation/[NetApp SolidFire Resources Page^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[Documentation for earlier versions of NetApp SolidFire and Element products^]
