---
permalink: esds/task_esds_uninstall.html
sidebar: sidebar
keywords: solidfire esds, uninstalling solidfire esds, ansible role
summary: You can “reset” a node on which you installed SolidFire eSDS by removing SolidFire eSDS on the node. To reinstate SolidFire eSDS on the node, you should perform all the installation steps.
---

= Uninstall SolidFire eSDS on the node
:icons: font
:imagesdir: ../media/

[.lead]
You can *reset* a node on which you installed SolidFire eSDS by removing SolidFire eSDS on the node. To reinstate SolidFire eSDS on the node, you should perform all the installation steps.

NOTE: You can use the link:https://github.com/NetApp-Automation/nar_solidfire_sds_uninstall[`nar_solidfire_sds_uninstall`^] Ansible role provided by NetApp to perform the operation. If you want to manually remove SolidFire eSDS on the node, see the steps below.

.Steps

. Remove drives from the cluster by using the Element UI or the https://docs.netapp.com/us-en/element-software/docs/api/reference_element_api_removedrives.html[`RemoveDrives`^] API method.
+
This results in the system migrating data from the node's drives to other drives in the cluster. The time this process takes is dependent on how much data must be migrated.

. Remove the node from the cluster using either the Element UI or the https://docs.netapp.com/us-en/element-software/docs/api/reference_element_api_removenodes.html[`RemoveNodes`^] API method.
. Use SSH to connect to the node that is removed from the cluster.
. Remove SolidFire eSDS from the node as follows:
+
----
yum remove solidfire-element
----

. Remove persistent data from the directory as follows:
+
----
rm -rf /opt/sf
----

== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation/[NetApp SolidFire Resources Page^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html[Documentation for earlier versions of NetApp SolidFire and Element products^]
