---
permalink: api/reference_element_api_getlicensekey.html
sidebar: sidebar
keywords: cluster,get,getting,license,key
summary: 'On SolidFire Enterprise SDS storage clusters, you can use the GetLicenseKey method to retrieve the current license key for the storage cluster. The license key for a storage cluster consists of the cluster’s order number combined with the serial number, and activates the capacity model you have purchased for Element software.'
---

= GetLicenseKey
:icons: font
:imagesdir: ../media/

[.lead]
On SolidFire Enterprise SDS storage clusters, you can use the `GetLicenseKey` method to retrieve the current license key for the storage cluster. The license key for a storage cluster consists of the cluster's order number combined with the serial number, and activates the capacity model you have purchased for Element software.

== Parameters

This method has no input parameters.

== Return values

This method has the following return values:

[options="header"]
|===
|Name |Description |Type
a|
orderNumber
a|
The sales order number of the storage cluster.
a|
string
a|
serialNumber
a|
The serial number of the storage cluster.
a|
string
|===

== Request example

Requests for this method are similar to the following example:

----
{
   "method": "GetLicenseKey",
   "params": {
     },
   "id": 1
}
----

== Response example

This method returns a response similar to the following example:

----
{
   "id" : 1,
   "result" : {
      "serialNumber": "30G56E3WV",
      "orderNumber": "33601"
     }
   }
}
----

== New since version

12.2
